const DB_NAME='daily-ledger-db', DB_VERSION=1;
let db, state={account:null,categories:[],transactions:[],budgets:[],month:new Date().toISOString().slice(0,7),page:'dashboard'};
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(Number(n)||0), today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{db=r.result;['account','categories','transactions','budgets'].forEach(s=>{if(!db.objectStoreNames.contains(s))db.createObjectStore(s,{keyPath:'id',autoIncrement:true})})};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function all(store){return new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(store,obj){return new Promise((res,rej)=>{const r=db.transaction(store,'readwrite').objectStore(store).put(obj);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function remove(store,id){return new Promise((res,rej)=>{const r=db.transaction(store,'readwrite').objectStore(store).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function hash(value){const data=new TextEncoder().encode(value), salt=new TextEncoder().encode('daily-ledger-v1');const key=await crypto.subtle.importKey('raw',data,'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:100000,hash:'SHA-256'},key,256);return [...new Uint8Array(bits)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function seed(){
  let a=await all('account');
  if(!a.length)await put('account',{username:'123',passwordHash:await hash('123'),updatedAt:new Date().toISOString()});
  if(!(await all('categories')).length){for(const c of [{name:'餐飲',type:'expense',color:'#356ae6'},{name:'交通',type:'expense',color:'#54b89c'},{name:'娛樂',type:'expense',color:'#f3af5b'},{name:'薪資',type:'income',color:'#d6789c'}])await put('categories',{...c,active:true})}
  // 首次啟動建立少量示範資料，方便立即查看總覽與報表。
  if(!(await all('transactions')).length&&!(await all('budgets')).length){
    const cats=await all('categories'), id=n=>cats.find(c=>c.name===n).id, month=new Date().toISOString().slice(0,7);
    const demo=[['薪資','income',50000,5,'本月薪資'],['餐飲','expense',380,10,'午餐與咖啡'],['交通','expense',120,12,'捷運與公車'],['娛樂','expense',650,15,'電影票']];
    for(const [cat,type,amount,day,note] of demo)await put('transactions',{date:`${month}-${String(day).padStart(2,'0')}`,type,categoryId:id(cat),amount,note,createdAt:new Date().toISOString()});
    for(const [cat,amount] of [['餐飲',5000],['交通',2500],['娛樂',2000]])await put('budgets',{month,categoryId:id(cat),amount});
  }
}
async function load(){state.account=(await all('account'))[0];state.categories=await all('categories');state.transactions=await all('transactions');state.budgets=await all('budgets')}
function notify(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),2200)}
function login(){document.body.innerHTML=`<div class="login"><div class="login-card"><div class="logo"><span class="logo-mark">$</span>日常記帳</div><h1>歡迎回來</h1><p class="muted">登入你的月預算管理工具</p><form id="loginForm"><label>帳號<input name="username" required autocomplete="username"></label><label>密碼<input name="password" type="password" required autocomplete="current-password"></label><button class="btn">登入</button><p id="loginError" class="danger-text"></p></form></div></div>`;$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);if(f.get('username')===state.account.username&&await hash(f.get('password'))===state.account.passwordHash){sessionStorage.logged='1';render()}else $('#loginError').textContent='帳號或密碼不正確，預設為 123／123'}}
const categoryName=id=>state.categories.find(c=>c.id==id)?.name||'未分類';
function monthTx(){return state.transactions.filter(t=>t.date.startsWith(state.month))}
function summary(){const tx=monthTx(),income=tx.filter(t=>t.type==='income').reduce((a,t)=>a+t.amount,0),expense=tx.filter(t=>t.type==='expense').reduce((a,t)=>a+t.amount,0),bud=state.budgets.filter(b=>b.month===state.month).reduce((a,b)=>a+b.amount,0);return {income,expense,bud,remaining:bud-expense,balance:income-expense}}
function shell(content){document.body.innerHTML=`<div class="layout"><aside class="sidebar"><div class="logo"><span class="logo-mark">$</span>日常記帳</div><nav class="nav">${[['dashboard','總覽'],['transactions','交易紀錄'],['categories','類別管理'],['budgets','月預算'],['reports','月報表'],['settings','帳號設定'],['help','功能說明']].map(([p,n])=>`<button data-page="${p}" class="${state.page===p?'active':''}">${n}</button>`).join('')}</nav><button id="logout" class="logout">登出</button></aside><main class="main">${content}</main></div><div id="modal" class="hidden"></div>`;document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});$('#logout').onclick=()=>{sessionStorage.removeItem('logged');login()}}
function header(title){return `<div class="topbar"><h1>${title}</h1><div class="month-picker"><button class="btn secondary" id="themeToggle" type="button">${document.documentElement.classList.contains('dark')?'☀️ 淺色模式':'🌙 暗黑模式'}</button><label>檢視月份<input id="month" type="month" value="${state.month}"></label></div></div>`}
function dashboard(){const s=summary(),tx=monthTx(),by={};tx.filter(t=>t.type==='expense').forEach(t=>by[t.categoryId]=(by[t.categoryId]||0)+t.amount);const rows=state.categories.filter(c=>c.type==='expense'&&by[c.id]).sort((a,b)=>(by[b.id]||0)-(by[a.id]||0)).slice(0,5);return header('月度總覽')+`<div class="grid stats"><div class="card stat"><div class="label">本月收入</div><div class="value income">${money(s.income)}</div></div><div class="card stat"><div class="label">本月支出</div><div class="value expense">${money(s.expense)}</div></div><div class="card stat"><div class="label">本月結餘</div><div class="value balance">${money(s.balance)}</div></div><div class="card stat"><div class="label">預算剩餘</div><div class="value ${s.remaining<0?'expense':'budget'}">${money(s.remaining)}</div></div></div><div class="grid two-col" style="margin-top:18px"><section class="card"><div class="section-title"><h2>類別支出</h2><button class="btn secondary small" data-page="reports">查看報表</button></div>${rows.length?rows.map(c=>{const amount=by[c.id],budget=state.budgets.find(b=>b.month===state.month&&b.categoryId==c.id)?.amount||0,pct=budget?Math.min(amount/budget*100,100):Math.min(amount/(s.expense||1)*100,100);return `<div class="bar-row"><span>${esc(c.name)}</span><div class="bar ${budget&&amount>budget?'over':''}"><span style="width:${pct}%"></span></div><strong>${money(amount)}</strong></div>`}).join(''):'<div class="empty">本月尚無支出資料</div>'}</section><section class="card"><div class="section-title"><h2>最近交易</h2><button class="btn small" id="addTx">新增交易</button></div>${tx.sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(t=>`<div class="bar-row" style="grid-template-columns:1fr auto"><span>${esc(categoryName(t.categoryId))}<small class="muted">　${esc(t.date)}</small></span><strong class="${t.type}">${t.type==='income'?'+':'-'}${money(t.amount)}</strong></div>`).join('')||'<div class="empty">尚無交易資料</div>'}</section></div>`}
function transactions(){let tx=monthTx();return header('交易紀錄')+`<div class="card"><div class="toolbar"><select id="typeFilter"><option value="">全部收支</option><option value="income">收入</option><option value="expense">支出</option></select><select id="catFilter"><option value="">全部類別</option>${state.categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')} </select><button class="btn" id="addTx">＋新增交易</button></div><div class="table-wrap"><table><thead><tr><th>日期</th><th>登錄時間</th><th>類別</th><th>類型</th><th>金額</th><th>備註</th><th></th></tr></thead><tbody id="txBody">${tx.sort((a,b)=>b.date.localeCompare(a.date)).map(t=>`<tr data-type="${t.type}" data-cat="${t.categoryId}"><td>${t.date}</td><td>${new Date(t.createdAt).toLocaleString('zh-TW')}</td><td>${esc(categoryName(t.categoryId))}</td><td><span class="badge ${t.type}">${t.type==='income'?'收入':'支出'}</span></td><td class="${t.type}"><strong>${t.type==='income'?'+':'-'}${money(t.amount)}</strong></td><td>${esc(t.note)}</td><td><button class="btn secondary small edit" data-id="${t.id}">編輯</button> <button class="btn danger small del" data-id="${t.id}">刪除</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">本月尚無交易資料</td></tr>'}</tbody></table></div></div>`}
function categories(){return header('類別管理')+`<div class="card"><div class="section-title"><h2>我的類別</h2><button class="btn" id="addCat">＋新增類別</button></div><div class="table-wrap"><table><thead><tr><th>名稱</th><th>類型</th><th>狀態</th><th></th></tr></thead><tbody>${state.categories.map(c=>`<tr><td><span class="dot" style="background:${c.color}"></span>${esc(c.name)}</td><td>${c.type==='income'?'收入':'支出'}</td><td><span class="badge ${c.active?'income':'neutral'}">${c.active?'使用中':'已停用'}</span></td><td><button class="btn secondary small edit-cat" data-id="${c.id}">編輯</button> <button class="btn danger small toggle-cat" data-id="${c.id}">${c.active?'停用':'啟用'}</button></td></tr>`).join('')}</tbody></table></div></div>`}
function budgets(){const list=state.categories.filter(c=>c.type==='expense');return header('月預算')+`<div class="card"><div class="section-title"><h2>${state.month} 類別預算</h2></div><form id="budgetForm"><div class="grid form-grid">${list.map(c=>{const b=state.budgets.find(x=>x.month===state.month&&x.categoryId==c.id);return `<label>${esc(c.name)}<input type="number" min="0" step="1" name="c${c.id}" value="${b?.amount||''}" placeholder="未設定"></label>`}).join('')}</div><div class="form-actions"><button class="btn">儲存預算</button></div></form></div>`}
function reports(){const s=summary(),tx=monthTx(),by={};tx.filter(t=>t.type==='expense').forEach(t=>by[t.categoryId]=(by[t.categoryId]||0)+t.amount);const total=s.expense||1;return header('月報表')+`<div class="grid stats"><div class="card stat"><div class="label">收入</div><div class="value income">${money(s.income)}</div></div><div class="card stat"><div class="label">支出</div><div class="value expense">${money(s.expense)}</div></div><div class="card stat"><div class="label">結餘</div><div class="value balance">${money(s.balance)}</div></div><div class="card stat"><div class="label">預算使用率</div><div class="value budget">${s.bud?Math.round(s.expense/s.bud*100):0}%</div></div></div><div class="grid two-col" style="margin-top:18px"><section class="card"><div class="section-title"><h2>各類別預算比較</h2></div>${state.categories.filter(c=>c.type==='expense').map(c=>{const a=by[c.id]||0,b=state.budgets.find(x=>x.month===state.month&&x.categoryId==c.id)?.amount||0,p=b?Math.min(a/b*100,100):0;return `<div class="bar-row"><span>${esc(c.name)}</span><div class="bar ${b&&a>b?'over':''}"><span style="width:${p}%"></span></div><span>${money(a)}${b?`／${money(b)}`:'／無預算'}</span></div>`}).join('')}</section><section class="card"><div class="section-title"><h2>支出占比</h2></div>${Object.keys(by).length?Object.entries(by).sort((a,b)=>b[1]-a[1]).map(([id,a])=>`<div class="bar-row"><span>${esc(categoryName(id))}</span><div class="bar"><span style="width:${a/total*100}%"></span></div><span>${Math.round(a/total*100)}%</span></div>`).join(''):'<div class="empty">本月尚無支出資料</div>'}</section></div>`}
function settings(){return header('帳號設定')+`<div class="card setting-grid"><h2>修改登入資訊</h2><p class="muted">修改後請使用新的帳號密碼登入。</p><form id="settingsForm"><label>新帳號<input name="username" value="${esc(state.account.username)}" required></label><label>目前密碼<input name="current" type="password" required></label><label>新密碼<input name="password" type="password" minlength="3" required></label><label>確認新密碼<input name="confirm" type="password" minlength="3" required></label><div class="form-actions"><button class="btn">儲存變更</button></div><p id="settingError" class="danger-text"></p></form></div>`}
function help(){return header('功能說明')+`<div class="grid two-col"><section class="card"><h2>快速開始</h2><p class="muted">第一次使用時，系統會準備幾筆示範資料，方便你先查看總覽與報表。之後可以直接新增、編輯或刪除資料。</p><div class="bar-row" style="grid-template-columns:36px 1fr"><strong class="balance">1</strong><span><strong>新增交易</strong><br><small class="muted">記錄收入或支出，登錄時間會由系統自動保存。</small></span></div><div class="bar-row" style="grid-template-columns:36px 1fr"><strong class="balance">2</strong><span><strong>設定類別</strong><br><small class="muted">可建立收入與支出類別，也可以停用不再使用的類別。</small></span></div><div class="bar-row" style="grid-template-columns:36px 1fr"><strong class="balance">3</strong><span><strong>設定月預算</strong><br><small class="muted">依月份與支出類別輸入預算金額。</small></span></div><div class="bar-row" style="grid-template-columns:36px 1fr"><strong class="balance">4</strong><span><strong>查看報表</strong><br><small class="muted">在總覽或月報表查看收入、支出、結餘與預算使用情況。</small></span></div></section><section class="card"><h2>各功能用途</h2><table><tbody><tr><td><strong>總覽</strong></td><td>查看指定月份的摘要與最近交易。</td></tr><tr><td><strong>交易紀錄</strong></td><td>新增、編輯、刪除及篩選收入／支出。</td></tr><tr><td><strong>類別管理</strong></td><td>管理收入與支出分類及顏色。</td></tr><tr><td><strong>月預算</strong></td><td>設定各支出類別的每月預算。</td></tr><tr><td><strong>月報表</strong></td><td>比較各類別實際支出與預算。</td></tr><tr><td><strong>帳號設定</strong></td><td>修改登入帳號與密碼。</td></tr></tbody></table></section></div><div class="card" style="margin-top:18px"><h2>登入資訊</h2><p class="muted">預設帳號與密碼皆為 <strong>123</strong>。資料保存在目前瀏覽器的本機資料庫中，不會自動同步到其他裝置。</p></div>`}
function modal(title,body){$('#modal').className='modal-backdrop';$('#modal').innerHTML=`<div class="modal"><div class="modal-head"><h2>${title}</h2><button class="close" id="close">×</button></div>${body}</div>`;$('#close').onclick=()=>$('#modal').className='hidden'}
function txForm(item={}){modal(item.id?'編輯交易':'新增交易',`<form id="txForm"><div class="grid form-grid"><label>交易日期<input name="date" type="date" value="${item.date||today()}" required></label><label>收支類型<select name="type" required><option value="expense" ${item.type==='expense'?'selected':''}>支出</option><option value="income" ${item.type==='income'?'selected':''}>收入</option></select></label></div><label>類別<select name="categoryId" required>${state.categories.filter(c=>c.active).map(c=>`<option value="${c.id}" ${item.categoryId==c.id?'selected':''}>${esc(c.name)}（${c.type==='income'?'收入':'支出'}）</option>`).join('')}</select></label><label>金額<input name="amount" type="number" min="1" step="1" value="${item.amount||''}" required></label><label>備註<textarea name="note" maxlength="200">${esc(item.note)}</textarea></label><div class="form-actions"><button type="button" class="btn secondary" id="cancel">取消</button><button class="btn">儲存</button></div></form>`);$('#cancel').onclick=()=>$('#modal').className='hidden';$('#txForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),obj={date:f.get('date'),type:f.get('type'),categoryId:Number(f.get('categoryId')),amount:Number(f.get('amount')),note:f.get('note'),createdAt:item.createdAt||new Date().toISOString()};if(item.id)obj.id=item.id;await put('transactions',obj);await load();$('#modal').className='hidden';notify('交易已儲存');render()}}
function catForm(item={}){modal(item.id?'編輯類別':'新增類別',`<form id="catForm"><label>名稱<input name="name" value="${esc(item.name)}" required maxlength="30"></label><label>類型<select name="type"><option value="expense" ${item.type!=='income'?'selected':''}>支出</option><option value="income" ${item.type==='income'?'selected':''}>收入</option></select></label><label>顏色<input name="color" type="color" value="${item.color||'#356ae6'}"></label><div class="form-actions"><button type="button" class="btn secondary" id="cancel">取消</button><button class="btn">儲存</button></div></form>`);$('#cancel').onclick=()=>$('#modal').className='hidden';$('#catForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),obj={name:f.get('name'),type:f.get('type'),color:f.get('color'),active:item.active??true};if(item.id)obj.id=item.id;await put('categories',obj);await load();$('#modal').className='hidden';render()}}
function bind(){const m=$('#month');if(m)m.onchange=()=>{state.month=m.value;render()};$('#themeToggle')?.addEventListener('click',()=>{document.documentElement.classList.toggle('dark');localStorage.setItem('ledger-theme',document.documentElement.classList.contains('dark')?'dark':'light');render()});$('#addTx')?.addEventListener('click',()=>txForm());document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>txForm(state.transactions.find(x=>x.id==b.dataset.id)));document.querySelectorAll('.del').forEach(b=>b.onclick=async()=>{if(confirm('確定刪除這筆交易？')){await remove('transactions',Number(b.dataset.id));await load();render()}});$('#addCat')?.addEventListener('click',()=>catForm());document.querySelectorAll('.edit-cat').forEach(b=>b.onclick=()=>catForm(state.categories.find(x=>x.id==b.dataset.id)));document.querySelectorAll('.toggle-cat').forEach(b=>b.onclick=async()=>{const c=state.categories.find(x=>x.id==b.dataset.id);c.active=!c.active;await put('categories',c);await load();render()});$('#budgetForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);for(const c of state.categories.filter(x=>x.type==='expense')){const amount=Number(f.get('c'+c.id));const old=state.budgets.find(b=>b.month===state.month&&b.categoryId==c.id);if(old&&amount===0)await remove('budgets',old.id);else if(amount>0)await put('budgets',{...(old||{}),month:state.month,categoryId:c.id,amount})}await load();notify('預算已儲存');render()});$('#settingsForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),error=$('#settingError');if(await hash(f.get('current'))!==state.account.passwordHash)return error.textContent='目前密碼不正確';if(f.get('password')!==f.get('confirm'))return error.textContent='兩次新密碼不一致';await put('account',{...state.account,username:f.get('username'),passwordHash:await hash(f.get('password')),updatedAt:new Date().toISOString()});await load();sessionStorage.removeItem('logged');login()});$('#typeFilter')?.addEventListener('change',filterTx);$('#catFilter')?.addEventListener('change',filterTx)}
function filterTx(){const type=$('#typeFilter').value,cat=$('#catFilter').value;document.querySelectorAll('#txBody tr').forEach(r=>{r.style.display=(!type||r.dataset.type===type)&&(!cat||r.dataset.cat===cat)?'':'none'})}
function render(){if(!sessionStorage.logged)return login();let content=state.page==='dashboard'?dashboard():state.page==='transactions'?transactions():state.page==='categories'?categories():state.page==='budgets'?budgets():state.page==='reports'?reports():state.page==='help'?help():settings();shell(content);bind()}
(async()=>{if(localStorage.getItem('ledger-theme')==='dark')document.documentElement.classList.add('dark');await openDB();await seed();await load();render()})().catch(e=>{document.body.innerHTML='<div class="login"><div class="login-card"><h1>資料庫無法啟用</h1><p class="muted">請使用支援 IndexedDB 的瀏覽器開啟本頁。</p></div></div>';console.error(e)});

