(() => {
  'use strict';
  const DAYS = ['一','二','三','四','五'];
  const PERIODS = [1,2,3,4,5,6,7,8];
  const KEYS = { teachers:'jhs_teachers', timetable:'jhs_timetable', config:'jhs_config' };
  const DEFAULT_TITLE = '教師課表查詢與多欄並排對照';
  const DEFAULT_PERIOD_TIMES = {1:{start:'08:00',end:'08:45'},2:{start:'08:55',end:'09:40'},3:{start:'10:00',end:'10:45'},4:{start:'10:55',end:'11:40'},5:{start:'13:10',end:'13:55'},6:{start:'14:05',end:'14:50'},7:{start:'15:10',end:'15:55'},8:{start:'16:05',end:'16:50'}};
  const sampleTeachers = [{id:'T001',title:'教師',name:'王小明',domain:'國文'},{id:'T002',title:'教師',name:'李雅婷',domain:'數學'},{id:'T003',title:'教師',name:'陳志豪',domain:'英文'},{id:'T004',title:'教師',name:'林怡君',domain:'自然'}];
  const sampleTimetable = [
    ['11','701','T001','國文'],['12','701','T002','數學'],['13','701','T003','英文'],['14','701','T004','自然'],['21','701','T002','數學'],['22','701','T001','國文'],['23','701','T004','自然'],['31','701','T003','英文'],['32','701','T001','國文'],['41','701','T002','數學'],['42','701','T003','英文'],['51','701','T004','自然'],
    ['11','702','T004','自然'],['12','702','T003','英文'],['13','702','T001','國文'],['14','702','T002','數學'],['21','702','T001','國文'],['22','702','T004','自然'],['23','702','T002','數學'],['31','702','T003','英文'],['32','702','T002','數學'],['41','702','T001','國文'],['42','702','T004','自然'],['51','702','T003','英文']
  ].map(([slot,classId,teacherId,subjectName], index) => ({serial:index + 1,classId,slot,subjectCode:'',subjectName,teacherId,teacherName:sampleTeachers.find(t => t.id === teacherId)?.name || ''}));
  let teachers, timetable, config;
  const $ = id => document.getElementById(id);
  const escapeHTML = value => String(value ?? '').replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const readJSON = (key, fallback) => { try { const v = JSON.parse(localStorage.getItem(key)); return Array.isArray(v) ? v : fallback; } catch { return fallback; } };
  const normalizeConfig = () => { config = config && typeof config === 'object' && !Array.isArray(config) ? config : {}; config.siteTitle = typeof config.siteTitle === 'string' && config.siteTitle.trim() ? config.siteTitle.trim() : DEFAULT_TITLE; config.adminPassword = typeof config.adminPassword === 'string' && config.adminPassword ? config.adminPassword : '123'; config.periodTimes = config.periodTimes && typeof config.periodTimes === 'object' ? config.periodTimes : {}; PERIODS.forEach(period => { const time = config.periodTimes[period] || {}; config.periodTimes[period] = {start:/^\d{2}:\d{2}$/.test(time.start) ? time.start : DEFAULT_PERIOD_TIMES[period].start,end:/^\d{2}:\d{2}$/.test(time.end) ? time.end : DEFAULT_PERIOD_TIMES[period].end}; }); };
  const load = () => { teachers = readJSON(KEYS.teachers, sampleTeachers); timetable = readJSON(KEYS.timetable, sampleTimetable); if (teachers.some(t => !Object.hasOwn(t, 'title'))) teachers = teachers.map(t => ({id:t.id,title:'',name:t.name,domain:''})); if (timetable.some(t => !Object.hasOwn(t, 'subjectName'))) timetable = timetable.map((t, index) => ({serial:index + 1,classId:t.classId,slot:t.slot,subjectCode:'',subjectName:t.subject || '',teacherId:t.teacherId,teacherName:getTeacher(t.teacherId)?.name || ''})); try { config = JSON.parse(localStorage.getItem(KEYS.config)) || {}; } catch { config = {}; } normalizeConfig(); };
  const save = () => { localStorage.setItem(KEYS.teachers, JSON.stringify(teachers)); localStorage.setItem(KEYS.timetable, JSON.stringify(timetable)); localStorage.setItem(KEYS.config, JSON.stringify(config)); };
  const notice = message => { $('status').textContent = message; };
  function populateSelect(id, entries, selected, placeholder) { const el = $(id); el.innerHTML = `<option value="">${escapeHTML(placeholder)}</option>` + entries.map(x => `<option value="${escapeHTML(x.value)}">${escapeHTML(x.label)}</option>`).join(''); el.value = selected || ''; }
  function syncSelectors() { const classes = [...new Set(timetable.map(x => x.classId))].sort(); const directory = new Map(teachers.map(x => [x.id, x])); timetable.forEach(x => { if (x.teacherId && !directory.has(x.teacherId)) directory.set(x.teacherId, {id:x.teacherId,title:'',name:x.teacherName || '',domain:''}); }); const teacherEntries = [...directory.values()].sort((a,b) => String(a.id).localeCompare(String(b.id), 'zh-Hant', {numeric:true})).map(x => ({value:x.id,label:`${x.id}｜${x.name || '未提供姓名'}${x.title ? '（' + x.title + '）' : ''}`})); populateSelect('classSelect', classes.map(x => ({value:x,label:x})), config.classId || classes[0], '— 選擇班級 —'); populateSelect('teacherSelect1', teacherEntries, config.teacher1 || teacherEntries[0]?.value, '— 選擇教師 —'); populateSelect('teacherSelect2', teacherEntries, config.teacher2 || teacherEntries[1]?.value, '— 選擇教師 —'); config.classId = $('classSelect').value; config.teacher1 = $('teacherSelect1').value; config.teacher2 = $('teacherSelect2').value; save(); }
  const getTeacher = id => teachers.find(t => t.id === id) || (() => { const item = timetable.find(x => x.teacherId === id); return item ? {id:item.teacherId,title:'',name:item.teacherName || '',domain:''} : undefined; })();
  function renderTable(entries, type) { const map = new Map(entries.map(item => [item.slot, item])); let html = '<table><thead><tr><th>節</th>' + DAYS.map(day => `<th>週${day}</th>`).join('') + '</tr></thead><tbody>';
    PERIODS.forEach(period => { const time=config.periodTimes[period]; html += `<tr><th><span class="period-number">第 ${period} 節</span><span class="period-label">${escapeHTML(time.start)}<br>${escapeHTML(time.end)}</span></th>`; DAYS.forEach((_, index) => { const item = map.get(`${index + 1}${period}`); if (!item) { html += '<td class="empty"></td>'; return; } const teacher = getTeacher(item.teacherId); const main = type === 'class' ? item.subjectName : item.classId; const sub = type === 'class' ? `${item.teacherId}${teacher ? '｜' + teacher.name : item.teacherName ? '｜' + item.teacherName : ''}` : item.subjectName; html += `<td data-class="${escapeHTML(item.classId)}" data-teacher="${escapeHTML(item.teacherId)}" title="點擊連動查詢"><span class="main-text ${type === 'teacher' ? 'teacher-main' : ''}">${escapeHTML(main)}</span><span class="sub-text">${escapeHTML(sub)}</span></td>`; }); html += '</tr>'; }); return html + '</tbody></table>'; }
  function render() { const classId = $('classSelect').value; const t1 = $('teacherSelect1').value; const t2 = $('teacherSelect2').value; const teacher1 = getTeacher(t1); const teacher2 = getTeacher(t2); $('siteTitle').textContent = config.siteTitle; document.title = config.siteTitle; $('classTitle').textContent = classId || '尚未選擇班級'; $('teacherTitle1').textContent = teacher1 ? `${teacher1.name}（${teacher1.id}）` : '尚未選擇教師'; $('teacherTitle2').textContent = teacher2 ? `${teacher2.name}（${teacher2.id}）` : '尚未選擇教師'; $('classSchedule').innerHTML = renderTable(timetable.filter(x => x.classId === classId), 'class'); $('teacherSchedule1').innerHTML = renderTable(timetable.filter(x => x.teacherId === t1), 'teacher'); $('teacherSchedule2').innerHTML = renderTable(timetable.filter(x => x.teacherId === t2), 'teacher'); document.querySelectorAll('#classSchedule td[data-teacher]').forEach(td => td.addEventListener('click', () => { $('teacherSelect1').value = td.dataset.teacher; changed('teacher1'); notice('已將該課程教師帶入「教師查詢 1」。'); })); document.querySelectorAll('#teacherSchedule1 td[data-class], #teacherSchedule2 td[data-class]').forEach(td => td.addEventListener('click', () => { $('classSelect').value = td.dataset.class; changed('classId'); notice('已將該課程班級帶入「班級查詢」。'); })); }
  function changed(key) { config[key] = key === 'classId' ? $('classSelect').value : $(key === 'teacher1' ? 'teacherSelect1' : 'teacherSelect2').value; save(); render(); }
  function parseCSV(text) { const lines = text.replace(/^\uFEFF/, '').replace(/\r/g,'').split('\n').filter(x => x.trim()); if (lines.length < 2) throw new Error('CSV 至少需包含標題列與一筆資料。'); return lines.map(line => { const values=[]; let cell='', quoted=false; for(let i=0;i<line.length;i++){ const c=line[i]; if(c==='"' && line[i+1]==='"'){cell+='"';i++;} else if(c==='"'){quoted=!quoted;} else if(c===','&&!quoted){values.push(cell.trim());cell='';} else {cell+=c;} } values.push(cell.trim()); return values; }); }
  function csvCell(v) { const s=String(v ?? ''); return /[",\n]/.test(s) ? `"${s.replace(/"/g,'""')}"` : s; }
  function download(filename, rows) { const blob = new Blob(['\uFEFF' + rows.map(row => row.map(csvCell).join(',')).join('\r\n')], {type:'text/csv;charset=utf-8'}); const link=document.createElement('a'); link.href=URL.createObjectURL(blob); link.download=filename; link.click(); URL.revokeObjectURL(link.href); }
  function downloadJSON(filename, value) { const blob = new Blob([JSON.stringify(value, null, 2)], {type:'application/json;charset=utf-8'}); const link=document.createElement('a'); link.href=URL.createObjectURL(blob); link.download=filename; link.click(); URL.revokeObjectURL(link.href); }
  function buildSettingsForm() { $('siteTitleInput').value = config.siteTitle; $('adminPasswordInput').value = config.adminPassword; $('periodTimeInputs').innerHTML = PERIODS.map(period => { const time=config.periodTimes[period]; return `<label class="period-time">第 ${period} 節<input type="time" data-period="${period}" data-bound="start" value="${escapeHTML(time.start)}" aria-label="第 ${period} 節上課時間"><input type="time" data-period="${period}" data-bound="end" value="${escapeHTML(time.end)}" aria-label="第 ${period} 節下課時間"></label>`; }).join(''); }
  function saveSettings() { const siteTitle=$('siteTitleInput').value.trim(); const adminPassword=$('adminPasswordInput').value; if (!siteTitle) { notice('網頁標題不可空白。'); return; } if (!adminPassword) { notice('管理密碼不可空白。'); return; } const periodTimes={}; for (const period of PERIODS) { const start=document.querySelector(`[data-period="${period}"][data-bound="start"]`).value; const end=document.querySelector(`[data-period="${period}"][data-bound="end"]`).value; if (!start || !end || start >= end) { notice(`第 ${period} 節的上下課時間無效。`); return; } periodTimes[period]={start,end}; } config.siteTitle=siteTitle; config.adminPassword=adminPassword; config.periodTimes=periodTimes; save(); render(); notice('網頁、節次與管理密碼已儲存。'); }
  function importConfig(event) { const file=event.target.files[0]; if(!file) return; const reader=new FileReader(); reader.onload=() => { try { const imported=JSON.parse(String(reader.result).replace(/^\uFEFF/, '')); if (!imported || typeof imported !== 'object' || Array.isArray(imported)) throw new Error('設定檔內容必須為 JSON 物件。'); config={...config,...imported}; normalizeConfig(); buildSettingsForm(); syncSelectors(); render(); notice('設定檔已匯入。'); } catch(error) { notice('設定檔匯入失敗：' + error.message); } event.target.value=''; }; reader.readAsText(file,'UTF-8'); }
  function importFile(event, kind) { const file=event.target.files[0]; if(!file) return; const reader=new FileReader(); reader.onload=() => { try { const expected = kind === 'teachers' ? '教師id,職稱,姓名,領域' : '流水號,班級編號,節次,科目代碼,科目名稱,教師id,教師姓名'; const bytes = reader.result; const utf8 = new TextDecoder('utf-8').decode(bytes); const big5 = new TextDecoder('big5').decode(bytes); const text = utf8.replace(/^\uFEFF/, '').split(/\r?\n/, 1)[0].trim() === expected ? utf8 : big5; const rows=parseCSV(text); const header=rows.shift().map(x => x.trim()); if(header.join(',') !== expected) throw new Error(`CSV 標題必須為：${expected}。`); if(kind==='teachers') { const values=rows.map(r => ({id:r[0],title:r[1],name:r[2],domain:r[3]})).filter(x=>x.id&&x.name); if(!values.length) throw new Error('沒有可匯入的教師資料。'); teachers=values; } else { const values=rows.map(r => ({serial:r[0],classId:r[1],slot:r[2],subjectCode:r[3],subjectName:r[4],teacherId:r[5],teacherName:r[6]})); if(!values.length || values.some(x => !/^[1-5][1-8]$/.test(x.slot) || !x.classId || !x.subjectName || !x.teacherId)) throw new Error('課表資料格式錯誤：節次必須為 11 至 58 的雙碼，且班級、科目名稱、教師 id 不可空白。'); timetable=values; } save(); syncSelectors(); render(); notice(`已成功匯入 ${kind==='teachers' ? teachers.length + ' 位教師' : timetable.length + ' 筆課表'}。`); } catch(error) { notice('匯入失敗：' + error.message); } event.target.value=''; }; reader.readAsArrayBuffer(file); }
  function openAdmin() { $('adminLoginPassword').value=''; $('adminLoginError').textContent=''; $('adminDialog').showModal(); $('adminLoginPassword').focus(); }
  function adminLogin(event) { event.preventDefault(); if ($('adminLoginPassword').value !== config.adminPassword) { $('adminLoginError').textContent='管理密碼不正確。'; return; } $('adminPanel').hidden=false; $('adminDialog').close(); notice('已進入系統管理，可進行資料匯入與設定。'); }
  function leaveAdmin(message) { $('adminPanel').hidden=true; $('adminLoginPassword').value=''; $('adminLoginError').textContent=''; document.querySelector('.control-panel').scrollIntoView({behavior:'smooth',block:'start'}); notice(message); }
  async function loadBundledData(force=false) { const missingTeachers = !localStorage.getItem(KEYS.teachers); const missingTimetable = !localStorage.getItem(KEYS.timetable); const missingConfig = force || !localStorage.getItem(KEYS.config); const mustLoadData = force || missingTeachers || missingTimetable; if (!mustLoadData && !missingConfig) return; try { const responses=await Promise.all(['data/config.json','data/teachers.csv','data/timetable.csv'].map(path => fetch(path))); if (responses.some(response => !response.ok && response.status !== 0)) throw new Error('找不到 data 預設檔案。'); const [configText,teachersText,timetableText]=await Promise.all(responses.map(response => response.text())); const bundledConfig=JSON.parse(configText.replace(/^\uFEFF/,'')); const teacherRows=parseCSV(teachersText); const timetableRows=parseCSV(timetableText); if (teacherRows.shift().join(',') !== '教師id,職稱,姓名,領域' || timetableRows.shift().join(',') !== '流水號,班級編號,節次,科目代碼,科目名稱,教師id,教師姓名') throw new Error('data 資料檔欄位格式不正確。'); if (mustLoadData) { teachers=teacherRows.map(row => ({id:row[0],title:row[1],name:row[2],domain:row[3]})).filter(row => row.id && row.name); timetable=timetableRows.map(row => ({serial:row[0],classId:row[1],slot:row[2],subjectCode:row[3],subjectName:row[4],teacherId:row[5],teacherName:row[6]})); } if (mustLoadData || missingConfig) config={...config,...bundledConfig}; normalizeConfig(); save(); } catch(error) { console.warn('無法載入 data 預設檔案，改用本機或範例資料。', error); throw error; } }
  async function initializeData() { if (!confirm('確定以 data 資料夾中的三個檔案重新初始化？目前瀏覽器中的設定、教師與課表資料將被覆蓋。')) return; try { await loadBundledData(true); buildSettingsForm(); syncSelectors(); render(); notice('初始化完成：已匯入 data 資料夾中的設定、教師與課表資料。'); } catch(error) { notice('初始化失敗：' + error.message); } }
  async function start() { load(); await loadBundledData(); init(); }
  function init() { load(); buildSettingsForm(); syncSelectors(); render(); ['classSelect','teacherSelect1','teacherSelect2'].forEach(id => $(id).addEventListener('change', () => changed(id==='classSelect'?'classId':id==='teacherSelect1'?'teacher1':'teacher2'))); $('saveSettings').addEventListener('click', saveSettings); $('configImport').addEventListener('change', importConfig); $('configExport').addEventListener('click',()=>downloadJSON('config.json', config)); $('teacherImport').addEventListener('change', e=>importFile(e,'teachers')); $('timetableImport').addEventListener('change', e=>importFile(e,'timetable')); $('teacherExport').addEventListener('click',()=>download('teachers.csv',[['教師id','職稱','姓名','領域'],...teachers.map(x=>[x.id,x.title,x.name,x.domain])])); $('timetableExport').addEventListener('click',()=>download('timetable.csv',[['流水號','班級編號','節次','科目代碼','科目名稱','教師id','教師姓名'],...timetable.map(x=>[x.serial,x.classId,x.slot,x.subjectCode,x.subjectName,x.teacherId,x.teacherName])])); $('initializeData').addEventListener('click', initializeData); $('resetData').addEventListener('click',()=>{ if(confirm('確定還原範例資料？目前本機資料將被取代。')) { teachers=sampleTeachers; timetable=sampleTimetable; config={}; normalizeConfig(); save(); buildSettingsForm(); syncSelectors(); render(); notice('已還原範例資料。'); } }); $('clearData').addEventListener('click',()=>{ if(confirm('確定清除所有本機課表資料？')) { localStorage.removeItem(KEYS.teachers); localStorage.removeItem(KEYS.timetable); localStorage.removeItem(KEYS.config); teachers=[]; timetable=[]; config={}; normalizeConfig(); buildSettingsForm(); syncSelectors(); render(); notice('本機資料已清除。'); } }); }
  start();
  $('adminButton').addEventListener('click', openAdmin);
  $('adminLoginForm').addEventListener('submit', adminLogin);
  $('adminCancel').addEventListener('click', () => $('adminDialog').close());
  $('backToQuery').addEventListener('click', () => leaveAdmin('已回到課表查詢。'));
  $('logoutButton').addEventListener('click', () => leaveAdmin('已登出系統管理。'));
})();
